import_name: 'ArkanaKeys' # Optional. Name of the framework to be imported. Defaults to ArkanaKeys.
namespace: 'ArkanaKeys' # Optional. Namespace used to access the secrets in the codebase. Defaults to ArkanaKeys.
pod_name: 'ArkanaKeys' # Optional. Name of the pod to be declared in your Podfile. Defaults to ArkanaKeys.
result_path: 'ArkanaKeys' # Optional. Destination path of the generated code, related to the path of this config file. Defaults to ArkanaKeys.
flavors: # Optional. Flavors are keywords added as a prefix to every secret when reading them from environment variables. This is useful for instance in white-label projects. Check the "Usage" section of the README for more information.
swift_declaration_strategy: let # Optional. One of: lazy var, var, let. Defaults to let.
should_generate_unit_tests: true # Optional. One of: true, false. Defaults to true.
package_manager: spm # Optional. One of: spm, cocoapods. If you use both, declare cocoapods. Defaults to spm.
global_secrets: # Optional. List of secrets that are the same regardless of which environment is being built. Defaults to empty.
  - TeamId
  - KeyId
  - PrivateKey
